# Generated by Django 3.2.7 on 2023-09-12 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=123)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='post/images')),
                ('web_site', models.URLField(max_length=123)),
                ('email', models.EmailField(max_length=123)),
                ('phone_number', models.CharField(max_length=123)),
                ('location', models.CharField(max_length=123)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
