# Generated by Django 3.2.7 on 2023-09-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField()),
                ('logo', models.ImageField(upload_to='post/images')),
                ('youtube', models.URLField()),
                ('facebook', models.URLField()),
                ('github', models.URLField()),
            ],
        ),
    ]
